- name: remove old rsyslog conf files
  command: rm /etc/rsyslog.conf
  args:
    removes: /etc/rsyslog.conf
- command: rm /etc/rsyslog.d/50-default.conf
  args:
    removes: /etc/rsyslog.d/50-default.conf
- command: rm /etc/rsyslog.d/20-ufw.conf
  args:
    removes: /etc/rsyslog.d/20-ufw.conf
- command: rm /etc/rsyslog.d/21-cloudinit.conf
  args:
    removes: /etc/rsyslogd/21-cloudinit.conf


- name: create rsyslog.conf file 
  template:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644

- name: Create rsyslog ufw configuration file
  template:
    src: 20-ufw.conf
    dest: /etc/rsyslog.d/20-ufw.conf
    owner: root
    group: root
    mode: 0644

- name: Create rsyslog default configuration file
  template:
    src: 50-default.conf
    dest: /etc/rsyslog.d/50-default.conf
    owner: root
    group: root
    mode: 0644

- name: Create custom specific configuration files
  template:
    src: custom.conf
    dest: /etc/rsyslog.d/{{ item.priority }}-{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ rsyslog_apps }}"

- name: Create rsyslog cloudinit configuration file
  template:
    src: 21-cloudinit.conf
    dest: /etc/rsyslog.d/21-cloudinit.conf
    owner: root
    group: root
    mode: 0644
